name: GeneratePlantumlImages

on:
  push:
    branches: [ '*' ]
    paths: [ 'src/plantuml/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Generate images
        run: |
          mkdir -p images/plantuml
          rm -rf images/plantuml/*
          for fullname in src/plantuml/*.puml
          do
            base=$(basename -- "$fullname")
            echo ${base%.*}
            curl --silent --show-error --fail -H "Content-Type: text/plain" --data-binary @- https://plantuml.gematik.solutions/plantuml/svg/ --output - < "src/plantuml/${base%.*}.puml" > "images/plantuml/${base%.*}.svg"
          done

#curl --silent --show-error --fail -H "Content-Type: text/plain" \
#            --data-binary @- https://plantuml.gematik.solutions/plantuml/svg/ \
#            --output - < src/plantuml/${puml_file}.puml > images/${puml_file}.svg
#          curl --silent --show-error --fail -H "Content-Type: text/plain" \
#            --data-binary @- https://plantuml.gematik.solutions/plantuml/png/ \
#            --output - < src/plantuml/${puml_file}.puml > images/${puml_file}.png
